# Generated by Django 5.2.4 on 2025-07-25 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trees', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plantedtree',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planted_trees', to='users.account'),
        ),
        migrations.AddField(
            model_name='plantedtree',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planted_trees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantedtree',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantings', to='trees.tree'),
        ),
        migrations.AddIndex(
            model_name='plantedtree',
            index=models.Index(fields=['user', 'account'], name='trees_plant_user_id_37f826_idx'),
        ),
    ]
